### PR TITLE
Add VisibleForTesting annotation

### PR DESCRIPTION
**Pull request by dkuwahara**
Fix some of the Codacy package private issues by marking them as intentionally package private

### CODE REVIEW

**Comment by yshewchuk** [comment]
What's the purpose for adding these? Are tests currently failing? Are you planning on adding more tests?

**Comment by dkuwahara** [comment]
This should resolve a bunch of the Codacy issues

**Comment by yshewchuk** [comment]
Ah, according to the codacy report this does not impact the issues. I think that actually what it is expecting for them is that we explicitly mark them as either private or protected.

**Comment by dkuwahara** [comment]
If you look at the PR details you'll see under "Fixed Issues" https://app.codacy.com/app/yshewchuk/accelerator-initializer/pullRequest?prid=2018178
Codacy recommends using the Annotation for things intentionally package private

**Pull request merged**
