### PR TITLE
Apply spring-javaformat plugin

### PR DESCRIPTION
**Pull request by eddumelendez**
See gh-8

### CODE REVIEW

**Comment by dkuwahara** [comment]
Is this using tabs instead of spaces now?

**Comment by yshewchuk** [comment]
Yes, it looks like the spring framework convention uses tabs rather than spaces. 

I took a look at this plugin, and it's nice that it's so easy to use, but it's a little bit unfortunate that the actual style that it enforces doesn't seem to be readily documented. Also, we will need to enable checkstyle, potentially with codacy. I was planning on updating the project to use the google style conventions since that's what everyone seems to be familiar with.  Do you know what the major differences are in the styles? From what I see it may mostly just be spacing?

**Comment by yshewchuk** [comment]
@eddumelendez are you aware of anywhere where the style it enforces is documented? Or do you know what the differences are from Google's standard?

**Comment by yshewchuk** [comment]
Closing this one for now since it conflicts with other changes, and the documentation is not clear on what the standards it enforces are. Will investigate further when there is more time available.

**Pull request closed without merging**
