### PR TITLE
Update README.md Codacy badge

### PR DESCRIPTION
**Pull request by dkuwahara**
Codacy badge linking to personal fork

### CODE REVIEW

**Comment by yshewchuk** [comment]
I've approved but also changed, please look over the change I made before merging

**Comment by yshewchuk** [comment]
lol wrong button

**Comment by dkuwahara** [comment]
It doesn't use the GitHub org ?

**Comment by yshewchuk** [comment]
No, that portion of the URL is the codacy account name, I guess.

**Comment by yshewchuk** [comment]
You can see that the current rating has been updated to A even though I haven't merged back to my fork yet.

**Pull request merged**
